import { pgTable, text, boolean, timestamp, integer, pgEnum, uuid, numeric, date, index } from "drizzle-orm/pg-core";

// Enums
export const userRoleEnum = pgEnum("user_role", ["rf", "kunde", "admin"]);
export const companyTypeEnum = pgEnum("company_type", ["AS", "ENK", "NUF"]);
export const processModelEnum = pgEnum("process_model", ["aarsbasert", "loepende"]);
export const taskTypeEnum = pgEnum("task_type", [
  "dokument_opplasting",
  "bekreftelse",
  "godkjenning",
  "signering",
]);
export const taskStatusEnum = pgEnum("task_status", [
  "ikke_startet",
  "levert",
  "godkjent",
  "trenger_mer",
]);
export const cycleStatusEnum = pgEnum("cycle_status", [
  "aktiv",
  "fullfort",
  "kansellert",
]);
export const documentStatusEnum = pgEnum("document_status", [
  "lastet_opp",
  "godkjent_av_rf",
  "avvist",
]);
export const documentCategoryEnum = pgEnum("document_category", [
  "bilag",
  "bankutskrift",
  "aapningsbalanse",
  "annet",
]);
export const approvalTypeEnum = pgEnum("approval_type", [
  "aarsregnskap",
  "generalforsamling",
]);
export const contactRoleEnum = pgEnum("contact_role", [
  "daglig_leder",
  "styreleder",
  "okonomiansvarlig",
  "annet",
]);

// Users
export const users = pgTable("users", {
  id: uuid("id").defaultRandom().primaryKey(),
  email: text("email").notNull().unique(),
  name: text("name").notNull(),
  passwordHash: text("password_hash"),
  role: userRoleEnum("role").notNull().default("kunde"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Accountants
export const accountants = pgTable("accountants", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: uuid("user_id")
    .references(() => users.id)
    .notNull()
    .unique(),
  firmName: text("firm_name"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Companies
export const companies = pgTable("companies", {
  id: uuid("id").defaultRandom().primaryKey(),
  orgNr: text("org_nr").notNull().unique(),
  name: text("name").notNull(),
  companyType: companyTypeEnum("company_type").notNull().default("AS"),
  vatRegistered: boolean("vat_registered").notNull().default(false),
  hasEmployees: boolean("has_employees").notNull().default(false),
  processModel: processModelEnum("process_model")
    .notNull()
    .default("aarsbasert"),
  address: text("address"),
  industryCode: text("industry_code"),
  foundedDate: text("founded_date"),
  accountantId: uuid("accountant_id")
    .references(() => accountants.id)
    .notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Contacts (customer users linked to companies)
export const contacts = pgTable("contacts", {
  id: uuid("id").defaultRandom().primaryKey(),
  companyId: uuid("company_id")
    .references(() => companies.id)
    .notNull(),
  userId: uuid("user_id").references(() => users.id),
  name: text("name").notNull(),
  email: text("email").notNull(),
  role: contactRoleEnum("role").notNull().default("daglig_leder"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Cycles (accounting year)
export const cycles = pgTable("cycles", {
  id: uuid("id").defaultRandom().primaryKey(),
  companyId: uuid("company_id")
    .references(() => companies.id)
    .notNull(),
  year: integer("year").notNull(),
  status: cycleStatusEnum("status").notNull().default("aktiv"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  completedAt: timestamp("completed_at"),
});

// Tasks (generated by process engine)
export const tasks = pgTable("tasks", {
  id: uuid("id").defaultRandom().primaryKey(),
  cycleId: uuid("cycle_id")
    .references(() => cycles.id)
    .notNull(),
  title: text("title").notNull(),
  description: text("description").notNull(),
  helpText: text("help_text"),
  type: taskTypeEnum("type").notNull(),
  sortOrder: integer("sort_order").notNull(),
  required: boolean("required").notNull().default(true),
  status: taskStatusEnum("status").notNull().default("ikke_startet"),
  deadlineRelative: text("deadline_relative"),
  deliveredAt: timestamp("delivered_at"),
  approvedAt: timestamp("approved_at"),
  rfComment: text("rf_comment"),
});

// Documents
export const documents = pgTable("documents", {
  id: uuid("id").defaultRandom().primaryKey(),
  taskId: uuid("task_id")
    .references(() => tasks.id),                        // Nullable: null for RF-opplastede dokumenter
  companyId: uuid("company_id")
    .references(() => companies.id)
    .notNull(),
  cycleId: uuid("cycle_id")
    .references(() => cycles.id)
    .notNull(),
  category: documentCategoryEnum("category").notNull().default("bilag"),
  originalFilename: text("original_filename").notNull(),
  storedPath: text("stored_path").notNull(),
  fileType: text("file_type").notNull(),
  fileSize: integer("file_size").notNull(),
  uploadedBy: uuid("uploaded_by")
    .references(() => users.id)
    .notNull(),
  uploadedAt: timestamp("uploaded_at").defaultNow().notNull(),
  status: documentStatusEnum("status").notNull().default("lastet_opp"),
  rejectionReason: text("rejection_reason"),
});

// Approvals
export const approvals = pgTable("approvals", {
  id: uuid("id").defaultRandom().primaryKey(),
  companyId: uuid("company_id")
    .references(() => companies.id)
    .notNull(),
  cycleId: uuid("cycle_id")
    .references(() => cycles.id)
    .notNull(),
  documentId: uuid("document_id").references(() => documents.id),
  type: approvalTypeEnum("type").notNull(),
  approvedBy: uuid("approved_by")
    .references(() => users.id)
    .notNull(),
  approvedAt: timestamp("approved_at").defaultNow().notNull(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
});

// Notifications
export const notifications = pgTable("notifications", {
  id: uuid("id").defaultRandom().primaryKey(),
  recipientUserId: uuid("recipient_user_id")
    .references(() => users.id)
    .notNull(),
  recipientEmail: text("recipient_email").notNull(),
  type: text("type").notNull(),
  companyId: uuid("company_id").references(() => companies.id),
  content: text("content").notNull(),
  sentAt: timestamp("sent_at"),
  readAt: timestamp("read_at"),
  channel: text("channel").notNull().default("epost"),
  relatedTaskId: uuid("related_task_id").references(() => tasks.id),
});

// Invitations
export const invitations = pgTable("invitations", {
  id: uuid("id").defaultRandom().primaryKey(),
  companyId: uuid("company_id")
    .references(() => companies.id)
    .notNull(),
  email: text("email").notNull(),
  token: text("token").notNull().unique(),
  expiresAt: timestamp("expires_at").notNull(),
  acceptedAt: timestamp("accepted_at"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// ═══════════════════════════════════════════════════════════════════════
// REGNSKAPSMODUL — Dobbel bokføring basert på NS 4102
// ═══════════════════════════════════════════════════════════════════════

export const accountClassEnum = pgEnum("account_class", [
  "eiendeler",       // 1000-1999
  "egenkapital",     // 2000-2099
  "gjeld",           // 2100-2999
  "inntekter",       // 3000-3999
  "varekostnad",     // 4000-4999
  "lonnskostnad",    // 5000-5999
  "avskrivninger",   // 6000-6999
  "andre_kostnader", // 7000-7999
  "finans",          // 8000-8999
]);

export const voucherStatusEnum = pgEnum("voucher_status", [
  "utkast",        // AI har foreslått kontering, RF har ikke sett
  "foreslatt",     // AI-foreslått, venter på RF
  "godkjent",      // RF har godkjent posteringen
  "postert",       // Bokført i hovedbok
  "avvist",        // RF avviste AI-forslaget
]);

export const bankLineStatusEnum = pgEnum("bank_line_status", [
  "uavstemt",      // Ikke koblet til noen postering
  "avstemt",       // Koblet til bilagspostering
  "ignorert",      // Manuelt markert som ikke relevant
]);

// Kontoplan — NS 4102 standardkontoer + selskapsspesifikke
export const accounts = pgTable("accounts", {
  id: uuid("id").defaultRandom().primaryKey(),
  companyId: uuid("company_id")
    .references(() => companies.id)
    .notNull(),
  accountNumber: integer("account_number").notNull(), // 1000-8999
  name: text("name").notNull(),
  accountClass: accountClassEnum("account_class").notNull(),
  isStandard: boolean("is_standard").notNull().default(true), // NS 4102 standard
  active: boolean("active").notNull().default(true),
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, (table) => [
  index("accounts_company_number_idx").on(table.companyId, table.accountNumber),
]);

// Bilag (vouchers) — samler posteringene for én transaksjon
export const vouchers = pgTable("vouchers", {
  id: uuid("id").defaultRandom().primaryKey(),
  companyId: uuid("company_id")
    .references(() => companies.id)
    .notNull(),
  cycleId: uuid("cycle_id")
    .references(() => cycles.id)
    .notNull(),
  voucherNumber: integer("voucher_number").notNull(), // Løpende bilagsnummer per år
  voucherDate: date("voucher_date").notNull(),        // Transaksjonsdato
  description: text("description").notNull(),
  documentId: uuid("document_id")                      // Lenke til opplastet fil
    .references(() => documents.id),
  status: voucherStatusEnum("status").notNull().default("utkast"),
  aiConfidence: numeric("ai_confidence", { precision: 3, scale: 2 }), // 0.00-1.00
  aiReasoning: text("ai_reasoning"),                   // AI sin begrunnelse for kontering
  createdBy: uuid("created_by")
    .references(() => users.id)
    .notNull(),
  approvedBy: uuid("approved_by")
    .references(() => users.id),
  approvedAt: timestamp("approved_at"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, (table) => [
  index("vouchers_company_cycle_idx").on(table.companyId, table.cycleId),
]);

// Posteringer (journal entries) — debet/kredit-linjer på bilag
export const journalEntries = pgTable("journal_entries", {
  id: uuid("id").defaultRandom().primaryKey(),
  voucherId: uuid("voucher_id")
    .references(() => vouchers.id)
    .notNull(),
  accountId: uuid("account_id")
    .references(() => accounts.id)
    .notNull(),
  debit: numeric("debit", { precision: 14, scale: 2 }).notNull().default("0"),
  credit: numeric("credit", { precision: 14, scale: 2 }).notNull().default("0"),
  description: text("description"), // Valgfri linjetekst
}, (table) => [
  index("journal_entries_voucher_idx").on(table.voucherId),
  index("journal_entries_account_idx").on(table.accountId),
]);

// Åpningsbalanse — IB per konto per syklus
export const openingBalances = pgTable("opening_balances", {
  id: uuid("id").defaultRandom().primaryKey(),
  companyId: uuid("company_id")
    .references(() => companies.id)
    .notNull(),
  cycleId: uuid("cycle_id")
    .references(() => cycles.id)
    .notNull(),
  accountId: uuid("account_id")
    .references(() => accounts.id)
    .notNull(),
  balance: numeric("balance", { precision: 14, scale: 2 }).notNull(), // Positiv = debet, negativ = kredit
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, (table) => [
  index("opening_balances_cycle_idx").on(table.companyId, table.cycleId),
]);

// Banklinjer — importerte transaksjoner fra bankutskrift
export const bankLines = pgTable("bank_lines", {
  id: uuid("id").defaultRandom().primaryKey(),
  companyId: uuid("company_id")
    .references(() => companies.id)
    .notNull(),
  cycleId: uuid("cycle_id")
    .references(() => cycles.id)
    .notNull(),
  documentId: uuid("document_id")                      // Bankutskrift-dokumentet
    .references(() => documents.id),
  transactionDate: date("transaction_date").notNull(),
  description: text("description").notNull(),
  amount: numeric("amount", { precision: 14, scale: 2 }).notNull(), // Positiv = inn, negativ = ut
  bankReference: text("bank_reference"),               // Referanse fra banken
  status: bankLineStatusEnum("status").notNull().default("uavstemt"),
  matchedVoucherId: uuid("matched_voucher_id")         // Koblet bilag ved avstemming
    .references(() => vouchers.id),
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, (table) => [
  index("bank_lines_company_cycle_idx").on(table.companyId, table.cycleId),
]);
